export const styles = {
  container: 'min-h-screen bg-background-light dark:bg-background-dark flex flex-col md:flex-row font-display',
  leftCol: 'w-full md:w-1/2 flex items-center justify-center p-8 lg:p-12 relative z-10 bg-surface-light dark:bg-surface-dark shadow-[4px_0_24px_rgba(0,0,0,0.05)] md:min-h-screen',
  formWrapper: 'max-w-md w-full',
  header: 'text-center mb-10',
  logoWrapper: 'inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-primary/10 mb-6 text-primary shadow-sm border border-primary/20',
  logoIcon: 'material-symbols-outlined text-[40px]',
  title: 'text-3xl font-bold text-text-main dark:text-white mb-2',
  subtitle: 'text-text-sub dark:text-gray-400',
  form: 'space-y-6',
  errorWrapper: 'bg-[#ffdad6] dark:bg-[#93000a] text-[#410002] dark:text-[#ffdad6] p-4 rounded-xl flex items-center gap-3 text-sm font-medium',
  inputGroup: 'relative group',
  inputIconWrapper: 'absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none',
  inputIcon: 'h-5 w-5 text-gray-500 dark:text-gray-400',
  input: 'block w-full pl-11 pr-4 pt-6 pb-2 bg-gray-100 dark:bg-gray-800 border-b-2 border-gray-400 dark:border-gray-600 rounded-t-xl text-text-main dark:text-white focus:outline-none focus:border-primary focus:bg-gray-200 dark:focus:bg-gray-700 transition-colors peer',
  label: 'absolute text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-4 z-10 origin-[0] left-11 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-4 peer-focus:text-primary dark:peer-focus:text-primary cursor-text',
  submitButton: 'w-full bg-primary hover:bg-primary/90 text-white font-medium py-3.5 px-4 rounded-full transition-all focus:ring-4 focus:ring-primary/30 disabled:opacity-50 disabled:cursor-not-allowed shadow-md hover:shadow-lg flex justify-center items-center h-12',
  spinner: 'w-6 h-6 border-2 border-white/30 border-t-white rounded-full animate-spin',
  forgotPasswordWrapper: 'text-center mt-6',
  forgotPasswordLink: 'text-sm font-medium text-primary hover:underline hover:text-primary/80 transition-colors',
  
  rightCol: 'hidden md:flex md:w-1/2 bg-[#d8e2ff] dark:bg-[#001a41] p-12 flex-col justify-center relative overflow-hidden',
  decorCircle1: 'absolute top-0 right-0 w-64 h-64 bg-primary/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3',
  decorCircle2: 'absolute bottom-0 left-0 w-96 h-96 bg-secondary/10 rounded-full blur-3xl translate-y-1/3 -translate-x-1/3',
  onboardingWrapper: 'max-w-lg mx-auto relative z-10',
  onboardingCard: 'bg-white/60 dark:bg-black/20 backdrop-blur-md border border-white/40 dark:border-white/10 rounded-3xl p-8 shadow-xl',
  onboardingHeader: 'flex items-center gap-3 mb-6',
  onboardingIconWrapper: 'p-2 bg-primary/20 dark:bg-primary/30 rounded-lg text-[#001a41] dark:text-[#d8e2ff]',
  onboardingTitle: 'text-2xl font-semibold text-[#001a41] dark:text-[#d8e2ff]',
  onboardingContent: 'space-y-6',
  newsItem: 'border-l-4 pl-4',
  newsTitle: 'font-semibold text-text-main dark:text-gray-200',
  newsText: 'text-sm text-text-sub dark:text-gray-400 mt-1',
  helpWrapper: 'mt-8 pt-6 border-t border-gray-300 dark:border-gray-700/50',
  helpLabel: 'text-sm text-text-sub dark:text-gray-400 font-medium tracking-wide',
  helpText: 'text-sm text-text-sub dark:text-gray-400 mt-1',
};
