export const styles = {
  overlay: 'fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-4 md:p-0',
  modal: 'bg-white dark:bg-background-dark border-4 border-text-main dark:border-white w-full md:w-[600px] h-full md:h-auto md:max-h-[90vh] rounded-none shadow-2xl flex flex-col slide-in',
  header: 'px-8 py-6 border-b-2 border-gray-200 dark:border-gray-800 flex justify-between items-center',
  title: 'text-2xl font-black text-text-main dark:text-white tracking-tighter uppercase',
  closeButton: 'text-text-main dark:text-white hover:opacity-70 transition-opacity',
  closeIcon: 'material-symbols-outlined text-[28px]',
  content: 'overflow-y-auto p-8 custom-scrollbar text-left flex-1',
  form: 'space-y-8',
  grid: 'grid grid-cols-2 gap-6',
  inputGroup: 'flex flex-col',
  label: 'block text-xs font-bold tracking-widest text-text-muted uppercase mb-2',
  select: 'w-full px-0 py-3 bg-transparent border-b-2 border-gray-200 dark:border-gray-800 focus:border-text-main dark:focus:border-white text-lg font-bold outline-none uppercase transition-colors appearance-none',
  amountInput: 'w-full px-0 py-3 bg-transparent border-b-2 border-gray-200 dark:border-gray-800 focus:border-text-main dark:focus:border-white text-3xl font-black tracking-tighter outline-none transition-colors',
  textInput: 'w-full px-0 py-3 bg-transparent border-b-2 border-gray-200 dark:border-gray-800 focus:border-text-main dark:focus:border-white text-lg font-bold outline-none transition-colors',
  dateInput: 'w-full px-0 py-3 bg-transparent border-b-2 border-gray-200 dark:border-gray-800 focus:border-text-main dark:focus:border-white font-bold outline-none transition-colors appearance-none',
  statusSelect: 'w-full px-0 py-3 bg-transparent border-b-2 border-gray-200 dark:border-gray-800 focus:border-text-main dark:focus:border-white font-bold outline-none uppercase transition-colors appearance-none text-sm',
  categorySelect: 'w-full px-0 py-3 bg-transparent border-b-2 border-gray-200 dark:border-gray-800 focus:border-text-main dark:focus:border-white font-bold outline-none transition-colors appearance-none  text-sm uppercase',
  errorText: 'text-xs text-danger font-bold mt-1 tracking-widest',
  checkboxWrapper: 'flex items-center gap-3 pt-4',
  checkbox: 'w-5 h-5 rounded-none border-2 border-text-main dark:border-white text-text-main bg-transparent focus:ring-0 checked:bg-text-main checked:border-text-main appearance-none cursor-pointer',
  checkboxLabel: 'text-xs font-bold tracking-widest text-text-main dark:text-white uppercase cursor-pointer select-none',
  footer: 'px-8 py-6 border-t-2 border-gray-200 dark:border-gray-800 flex justify-between items-center bg-transparent mt-auto',
  deleteButton: 'text-xs font-bold tracking-widest text-danger uppercase hover:opacity-70 transition-opacity flex items-center gap-2',
  deleteIcon: 'material-symbols-outlined text-[16px]',
  actionsWrapper: 'flex gap-4',
  cancelButton: 'px-6 py-3 bg-transparent text-text-main dark:text-white font-bold tracking-widest text-xs uppercase hover:opacity-70 transition-opacity',
  submitButton: 'px-8 py-3 bg-text-main dark:bg-white text-white dark:text-text-main font-bold tracking-widest text-xs uppercase hover:opacity-90 transition-opacity active:scale-95 rounded-none shadow-none',
};
