export const styles = {
  container: 'bg-background-light dark:bg-background-dark font-display text-text-main antialiased min-h-screen flex flex-col',
  header: 'sticky top-0 z-50 w-full border-b border-surface-light bg-background-light/95 backdrop-blur dark:bg-background-dark/95 dark:border-surface-dark',
  headerInner: 'mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8',
  logoWrapper: 'flex items-center gap-3',
  logoIconBox: 'flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary',
  logoIcon: 'material-symbols-outlined text-[28px]',
  logoText: 'text-xl font-bold tracking-tight text-text-main dark:text-white',
  loginButton: 'flex h-10 items-center justify-center rounded-full bg-primary px-6 text-sm font-medium text-white transition-colors hover:bg-primary/90 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary',
  
  main: 'flex-grow',
  mainInner: 'mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8',
  
  heroGrid: 'grid gap-12 lg:grid-cols-2 lg:gap-8 items-center py-12',
  heroTextCol: 'flex flex-col gap-6',
  heroBadge: 'inline-flex items-center rounded-full bg-primary/10 px-3 py-1 text-sm font-medium text-primary',
  heroTitle: 'text-4xl font-black tracking-tight text-text-main dark:text-white sm:text-5xl lg:text-6xl',
  heroSubtitle: 'max-w-xl text-lg text-text-sub dark:text-gray-300',
  heroActions: 'flex flex-wrap gap-4 pt-4',
  primaryHeroButton: 'flex h-12 min-w-[160px] items-center justify-center rounded-full bg-primary px-6 text-base font-semibold text-white shadow-sm transition-all hover:bg-primary/90 hover:shadow-hover',
  secondaryHeroButton: 'flex h-12 min-w-[160px] items-center justify-center rounded-full border border-gray-300 bg-white px-6 text-base font-semibold text-text-main shadow-sm transition-all hover:bg-gray-50 hover:border-gray-400 dark:bg-surface-dark dark:border-gray-700 dark:text-white dark:hover:bg-gray-800',
  heroImageWrapper: 'relative h-full min-h-[300px] w-full lg:h-[480px]',
  heroImage: 'absolute inset-0 rounded-2xl overflow-hidden shadow-xl bg-cover bg-center',
  heroImageOverlay: 'absolute inset-0 bg-gradient-to-t from-primary/20 to-transparent mix-blend-multiply',
  
  section: 'py-16',
  sectionHeader: 'mb-10',
  sectionTitle: 'text-3xl font-bold tracking-tight text-text-main dark:text-white',
  sectionSubtitle: 'mt-2 text-text-sub dark:text-gray-400',
  featuresGrid: 'grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4',
  featureCard: 'group relative flex flex-col gap-4 rounded-xl border border-gray-200 bg-white p-6 shadow-card transition-all hover:border-primary/50 hover:shadow-hover dark:border-gray-700 dark:bg-surface-dark',
  featureIconBox: (colorClass: string) => `flex h-12 w-12 items-center justify-center rounded-lg ${colorClass}`,
  featureIcon: 'material-symbols-outlined text-[28px]',
  featureTitle: 'text-lg font-bold text-text-main dark:text-white',
  featureText: 'mt-1 text-sm text-text-sub dark:text-gray-400',
  
  guideWrapper: 'rounded-2xl bg-surface-light p-8 dark:bg-surface-dark mt-8 mb-16',
  guideFlex: 'flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between',
  guideTextCol: 'lg:w-1/4',
  guideTitle: 'text-2xl font-bold text-text-main dark:text-white',
  guideSubtitle: 'text-text-sub dark:text-gray-400 mt-2',
  stepperWrapper: 'flex-1 lg:ml-12',
  stepperInner: 'relative flex items-center justify-between w-full',
  stepperLine: 'absolute left-0 top-1/2 h-0.5 w-full -translate-y-1/2 bg-gray-300 dark:bg-gray-700 lg:w-[95%]',
  stepItem: 'relative z-10 flex flex-col items-center gap-3 bg-surface-light px-2 dark:bg-surface-dark',
  stepIconActive: 'flex h-12 w-12 items-center justify-center rounded-full bg-primary text-white shadow-md ring-4 ring-surface-light dark:ring-surface-dark',
  stepIconInactive: 'flex h-12 w-12 items-center justify-center rounded-full bg-white text-text-sub border-2 border-gray-300 shadow-sm ring-4 ring-surface-light dark:bg-gray-800 dark:border-gray-600 dark:text-gray-300 dark:ring-surface-dark',
  stepIcon: 'material-symbols-outlined text-[24px]',
  stepLabelWrapper: 'text-center w-32',
  stepLabel: 'text-sm font-bold text-text-main dark:text-white',
  stepLabelMuted: 'text-sm font-medium text-text-main dark:text-gray-300',
  stepSub: 'text-xs text-text-sub dark:text-gray-400',
  
  footer: 'border-t border-gray-200 bg-white py-12 dark:border-gray-800 dark:bg-background-dark',
  footerInner: 'mx-auto flex max-w-7xl flex-col items-center gap-6 px-4 text-center sm:px-6 lg:px-8',
  footerLogo: 'flex items-center gap-2 text-text-main dark:text-white opacity-80',
  footerLinks: 'flex flex-wrap justify-center gap-8 text-sm font-medium text-text-sub dark:text-gray-400',
  footerLink: 'hover:text-primary dark:hover:text-primary transition-colors',
  footerCopyright: 'text-sm text-gray-500 dark:text-gray-600',
};
