export const styles = {
  container: 'w-full max-w-[1440px] mx-auto pb-24 md:pb-8 relative min-h-screen p-6',
  header: 'mb-12',
  title: 'text-5xl font-black text-text-main dark:text-white tracking-tighter uppercase leading-none',
  subtitleWrapper: 'flex items-center gap-4 mt-4',
  subtitleLine: 'h-[2px] w-12 bg-text-main dark:bg-white',
  subtitleText: 'text-xs font-black tracking-[0.3em] text-text-muted dark:text-gray-400 uppercase',
  section: 'space-y-12',
  kpiGrid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
  placeholderCard: 'p-8 border-2 border-dashed border-gray-200 dark:border-gray-800 flex flex-col items-center justify-center text-center opacity-50',
  placeholderIcon: 'material-symbols-outlined text-text-muted mb-2',
  placeholderText: 'text-[10px] font-bold uppercase tracking-widest text-text-muted',
  sectionTitle: 'text-xs font-black uppercase tracking-[0.3em] text-text-muted mb-6',
  bottomGrid: 'grid grid-cols-1 lg:grid-cols-2 gap-8 pt-8 border-t border-gray-100 dark:border-gray-800',
  widgetWrapper: 'space-y-4',
  widgetTitle: 'text-xs font-black uppercase tracking-[0.3em] text-text-muted',
  widgetContent: 'h-64 border-2 border-gray-50 dark:border-surface-dark flex items-center justify-center',
  widgetPlaceholder: 'text-[10px] font-bold uppercase tracking-widest text-text-muted italic',
};
