export const styles = {
  container: 'mb-10 w-full overflow-hidden',
  desktopWrapper: 'overflow-x-auto hidden md:block',
  table: 'w-full text-left border-collapse',
  theadRow: 'border-b-2 border-text-main dark:border-white text-text-main dark:text-white',
  th: 'px-2 py-4 text-xs font-bold tracking-widest uppercase',
  tbody: 'divide-y divide-gray-200 dark:divide-gray-800',
  tr: 'hover:bg-gray-50 dark:hover:bg-surface-dark transition-colors group',
  tdDate: 'px-2 py-5 whitespace-nowrap text-sm font-medium text-text-muted',
  tdDescription: 'px-2 py-5 font-bold text-text-main dark:text-white',
  recurringBadge: 'ml-3 border border-text-main dark:border-white text-text-main dark:text-white text-[9px] font-bold tracking-widest px-1.5 py-0.5 uppercase',
  tdCategory: 'px-2 py-5 text-sm font-medium text-text-muted',
  tdPayee: 'px-2 py-5 text-sm font-medium text-text-muted',
  tdAmount: (type: 'INCOME' | 'EXPENSE') => `px-2 py-5 text-base text-right font-black tracking-tight ${type === 'INCOME' ? 'text-text-main dark:text-white' : 'text-text-muted'}`,
  tdStatus: 'px-2 py-5 whitespace-nowrap',
  statusWrapper: 'flex items-center gap-2',
  statusDot: (status: 'PAID' | 'PENDING' | 'OVERDUE') => `w-2 h-2 rounded-full ${status === 'PAID' ? 'bg-success' : status === 'PENDING' ? 'bg-warning' : 'bg-danger'}`,
  statusText: 'text-xs font-bold tracking-widest uppercase text-text-main dark:text-white',
  tdActions: 'px-2 py-5 whitespace-nowrap text-right text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity',
  editButton: 'text-text-main dark:text-white hover:opacity-70 transition-opacity flex items-center justify-center ml-auto',
  emptyRow: 'px-2 py-10 text-center text-sm font-bold tracking-widest uppercase text-text-muted border-b border-gray-200 dark:border-gray-800',
  
  mobileWrapper: 'md:hidden flex flex-col gap-0 border-t-2 border-text-main dark:border-white',
  mobileItem: 'py-5 border-b border-gray-200 dark:border-gray-800 cursor-pointer active:bg-gray-50 dark:active:bg-surface-dark transition-colors',
  mobileHeader: 'flex justify-between items-start mb-3',
  mobileDescription: 'font-bold text-text-main dark:text-white leading-tight',
  mobileSub: 'text-xs font-bold tracking-widest uppercase text-text-muted mt-1',
  mobileAmount: (type: 'INCOME' | 'EXPENSE') => `font-black tracking-tight ${type === 'INCOME' ? 'text-text-main dark:text-white' : 'text-text-muted'}`,
  mobileFooter: 'flex justify-between items-center mt-3 pt-3',
  mobilePayee: 'text-xs font-medium text-text-muted truncate max-w-[50%]',
  mobileStatusDot: (status: 'PAID' | 'PENDING' | 'OVERDUE') => `w-1.5 h-1.5 rounded-full ${status === 'PAID' ? 'bg-success' : status === 'PENDING' ? 'bg-warning' : 'bg-danger'}`,
  mobileStatusText: 'text-[10px] font-bold tracking-widest uppercase text-text-main dark:text-white',
  mobileRecurringBadge: 'mt-3 block w-max border border-text-main dark:border-white text-text-main dark:text-white text-[9px] font-bold tracking-widest px-1.5 py-0.5 uppercase',
};
