export const styles = {
  overlay: 'fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-4 md:p-0',
  modal: 'bg-white dark:bg-background-dark border-4 border-text-main dark:border-white w-full md:w-[700px] h-full md:h-auto md:max-h-[90vh] rounded-none shadow-2xl flex flex-col slide-in',
  header: 'px-8 py-6 border-b-2 border-gray-200 dark:border-gray-800 flex justify-between items-center',
  title: 'text-2xl font-black text-text-main dark:text-white tracking-tighter uppercase',
  closeButton: 'text-text-main dark:text-white hover:opacity-70 transition-opacity',
  closeIcon: 'material-symbols-outlined text-[28px]',
  tabsWrapper: 'flex border-b-2 border-gray-200 dark:border-gray-800',
  tab: (isActive: boolean) => `flex-1 py-4 text-xs font-bold tracking-widest uppercase transition-colors ${
    isActive 
      ? 'bg-text-main text-white dark:bg-white dark:text-text-main' 
      : 'text-text-muted hover:bg-gray-50 dark:hover:bg-surface-dark'
  }`,
  content: 'overflow-y-auto p-8 custom-scrollbar flex-1 text-left',
  section: 'space-y-10',
  form: 'bg-gray-50 dark:bg-surface-dark p-6 border-2 border-gray-200 dark:border-gray-800',
  formTitle: 'text-xs font-black tracking-widest uppercase mb-6 text-text-main dark:text-white',
  grid: 'grid grid-cols-1 md:grid-cols-2 gap-6',
  grid3: 'grid grid-cols-1 md:grid-cols-3 gap-6',
  inputGroup: 'flex flex-col',
  label: 'block text-[10px] font-bold tracking-widest text-text-muted uppercase mb-2',
  input: 'w-full bg-transparent border-b-2 border-gray-200 dark:border-gray-700 py-2 text-sm font-bold outline-none focus:border-text-main dark:focus:border-white transition-colors',
  select: 'w-full bg-transparent border-b-2 border-gray-200 dark:border-gray-700 py-2 text-sm font-bold outline-none uppercase appearance-none',
  submitButton: 'mt-8 w-full bg-text-main dark:bg-white text-white dark:text-text-main py-3 text-xs font-bold tracking-widest uppercase hover:opacity-90 transition-opacity',
  listWrapper: 'space-y-4',
  listTitle: 'text-xs font-black tracking-widest uppercase text-text-main dark:text-white',
  listItem: 'py-4 flex justify-between items-center group',
  itemPrimary: 'font-bold text-text-main dark:text-white',
  itemSecondary: 'text-[10px] font-bold tracking-widest text-text-muted uppercase',
  deleteButton: 'opacity-0 group-hover:opacity-100 text-danger transition-opacity p-2',
  deleteIcon: 'material-symbols-outlined text-[18px]',
  emptyText: 'py-10 text-center text-xs font-bold tracking-widest text-text-muted uppercase',
  categoryGrid: 'grid grid-cols-1 md:grid-cols-2 gap-4',
  categoryCard: 'p-4 border-2 border-gray-100 dark:border-gray-800 flex justify-between items-center group',
  categoryInfo: 'flex items-center gap-3',
  categoryDot: (type: 'INCOME' | 'EXPENSE') => `w-2 h-2 rounded-full ${type === 'INCOME' ? 'bg-success' : 'bg-danger'}`,
  categoryName: 'text-sm font-bold text-text-main dark:text-white leading-none',
  categoryType: 'text-[9px] font-bold tracking-widest text-text-muted uppercase mt-1',
  footer: 'px-8 py-6 border-t-2 border-gray-200 dark:border-gray-800 flex justify-end items-center bg-gray-50 dark:bg-surface-dark mt-auto',
  footerButton: 'px-8 py-3 bg-text-main dark:bg-white text-white dark:text-text-main font-bold tracking-widest text-xs uppercase hover:opacity-90 transition-opacity active:scale-95 rounded-none',
};
